# Generated by Django 4.0.2 on 2022-02-22 12:56

from users.models import User

from django.db import migrations

from django.conf import settings
import os


def create_dev_admin_user(apps, schema_editor):
    if settings.DEBUG is True:
        User.objects.create_superuser(
            username=os.environ.get('DJANGO_SUPERUSER_USERNAME'),
            email=os.environ.get('DJANGO_SUPERUSER_EMAIL'),
            password=os.environ.get('DJANGO_SUPERUSER_PASSWORD'),

            first_name="admin",
            last_name="admin",
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dev_admin_user)
    ]
