# Generated by Django 4.0.2 on 2022-03-02 19:07

from product.models import *
from users.models import User

from django.db import migrations

from django.conf import settings


def add_dev_data(apps, schema_editor):
    if settings.DEBUG is True:
        category = Category.objects.create(name="CSS", order=1, is_active=True,)
        Category.objects.bulk_create([
            Category(name="NUST", order=2, is_active=True),
            Category(name="MDCAT", order=3, is_active=True),
            Category(name="ECAT", order=4, is_active=True),
            Category(name="ARMY", order=5, is_active=True),
        ])

        Subject.objects.create(name="English", description='Language Subject', order=1, is_active=True,)
        subject = Subject.objects.create(name="Compound", description='Multiple Subjects', order=2, is_active=True,)

        product = Product.objects.create(
            name="Ultimate CSS Screening Test Preparation Course",
            type='C',
            description="\"Challenge yourself until you master every concept.\"\r\n\r\nJoin our CSS Screening Test Facebook and WhatsApp Group Now!:\r\n- Score well with Special Tabir Academy Technique \r\n- Learning Box feature, explaining complex concepts\r\n- Gain access to top-quality MCQs from various difficulty levels (Low, Medium, and High)\r\n- Prepares you in just 30 Days\r\n- Solved Past Papers (Included)\r\n\r\nCover topics from All Subjects featured in the MPT/CSS Screening Test:\r\n1. Urdu (Grammar Usage and Translation)\r\n2. English (Vocabulary, Grammar, Comprehension)\r\n3. General Ability (Arithmetic, Algebra, Geometry, Logical Problem Solving, Analytical Problem Solving)\r\n4. General Knowledge ( Everyday Science, Pakistan Affairs, Current Affairs)\r\n5. Islamic Studies",
            slug='ultimate-css-screening-test-preparation-course',
            value=2450.0,
			discount=10.0,
			is_paid=True,
			is_active=True,
			meta_tag="css, css preparation, course, ultimate css screening",
			meta_description="Informative Lecture Series | Course Instructor Position Holder in CSS Exams | Interactive Learning Through Feedback & Evaluation | Enables Mastery of CSS Essay Concepts",
			category=category,
			subject=subject,
        )

        UserProduct.objects.create(
            product=product,
            user=User.objects.get(id=1),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('users', '0002_create_dev_admin_user'),
    ]

    operations = [
        migrations.RunPython(add_dev_data)
    ]
