# Generated by Django 4.0.2 on 2022-03-02 19:33

from product.models import Product
from content.models import Topic

from django.db import migrations

from django.conf import settings


def add_dev_manytomanyto_data(apps, schema_editor):
    if settings.DEBUG is True:
        product = Product.objects.get(id=1)
        product.topics.add(Topic.objects.get(id=1))


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_add_dev_data'),
        ('content', '0002_add_dev_data'),
    ]

    operations = [
        migrations.RunPython(add_dev_manytomanyto_data)
    ]
