# Generated by Django 4.0.2 on 2022-03-03 03:00

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_mock_test_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mock_test',
            field=models.JSONField(blank=True, default=product.models.mock_test_json_default),
        ),
    ]
