# Generated by Django 4.0.2 on 2022-03-02 19:07

from content.models import *

from django.db import migrations

from django.conf import settings


def add_dev_data(apps, schema_editor):
    if settings.DEBUG is True:
        answers = Answer.objects.bulk_create([
            Answer(content="2eˣ", is_correct=False, is_active=True,),
            Answer(content="1", is_correct=False, is_active=True,),
            Answer(content="eˣ", is_correct=True, is_active=True,),
            Answer(content="e²ˣ", is_correct=False, is_active=True,),
        ])

        question = Question.objects.create(
            content="What is the derivative of eˣ?",
			explanation="The differentiation of e to the power x is equal to e to the power x because the derivative of an exponential function with base 'e' is equal to ex. Mathematically, it is denoted as d(ex)/dx = ex. e to the power x is an exponential function with a base equal to 'e'. It is written as f(x) = ex, where 'e' is the Euler's number and its value is approximately 2.718. The differentiation of e to the power x can be done using different methods such as the first principle of differentiation and derivative of ax.",
			is_active=True,
        )
        question.answers.add(*answers)

        subtopic = SubTopic.objects.create(
            name="Differentiation",
			description="Math Sub Topic",
			slug="differentiation",
			is_active=True,
			order=1,
        )
        subtopic.questions.add(question)

        topic = Topic.objects.create(
            name="Calculus",
			description="Math Topic",
			slug="calculus",
			is_active=True,
			order=1,
        )
        topic.sub_topics.add(subtopic)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_dev_data)
    ]
