# Generated by Django 4.0.2 on 2022-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_dev_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ('order',), 'verbose_name': 'Sub Topic', 'verbose_name_plural': 'Sub Topics'},
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
